
--- ERROR LOG ---
Timestamp: 07-082025_22-01-24
Context: logs\MON5.2_Clone_test_run_2_3_2\error_log_07-08-2025_22-00-54.txt
Exception: Error in trend sampling thread
Traceback:
Traceback (most recent call last):
  File "c:\Users\FlowChemIR_User\Desktop\AGS Users\Meg\Automating-inline-IR-analysis-for-optimising-synthetic-reactions-MSc-project-1\main.py", line 205, in run_trend_sampler
    start_trend_sampling(
    ~~~~~~~~~~~~~~~~~~~~^
        db_path=db_path,
        ^^^^^^^^^^^^^^^^
    ...<7 lines>...
        stop_event=stop_event
        ^^^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: start_trend_sampling() got an unexpected keyword argument 'stop_event'
------------------------------------------------------------

--- ERROR LOG ---
Timestamp: 07-082025_22-01-24
Context: Child node 'ns=2;s=Local.iCIR.Probe1.Trends' does not support attribute 'Value'. Skipped. (BadAttributeIdInvalid)
Exception: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
Traceback:
Traceback (most recent call last):
  File "c:\Users\FlowChemIR_User\Desktop\AGS Users\Meg\Automating-inline-IR-analysis-for-optimising-synthetic-reactions-MSc-project-1\metadata_utils.py", line 23, in get_probe1_data
    value_of_node = child.get_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 155, in get_value
    result = self.get_data_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 164, in get_data_value
    return self.get_attribute(ua.AttributeIds.Value)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 276, in get_attribute
    result[0].StatusCode.check()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\ua\uatypes.py", line 218, in check
    raise UaStatusCodeError(self.value)
opcua.ua.uaerrors._auto.BadAttributeIdInvalid: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
------------------------------------------------------------

--- ERROR LOG ---
Timestamp: 07-082025_22-01-24
Context: Child node 'ns=2;s=Local.iCIR.Probe1.Triggers' does not support attribute 'Value'. Skipped. (BadAttributeIdInvalid)
Exception: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
Traceback:
Traceback (most recent call last):
  File "c:\Users\FlowChemIR_User\Desktop\AGS Users\Meg\Automating-inline-IR-analysis-for-optimising-synthetic-reactions-MSc-project-1\metadata_utils.py", line 23, in get_probe1_data
    value_of_node = child.get_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 155, in get_value
    result = self.get_data_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 164, in get_data_value
    return self.get_attribute(ua.AttributeIds.Value)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 276, in get_attribute
    result[0].StatusCode.check()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\ua\uatypes.py", line 218, in check
    raise UaStatusCodeError(self.value)
opcua.ua.uaerrors._auto.BadAttributeIdInvalid: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
------------------------------------------------------------

--- ERROR LOG ---
Timestamp: 07-082025_22-01-24
Context: Child node 'ns=2;s=Local.iCIR.Probe1.Methods' does not support attribute 'Value'. Skipped. (BadAttributeIdInvalid)
Exception: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
Traceback:
Traceback (most recent call last):
  File "c:\Users\FlowChemIR_User\Desktop\AGS Users\Meg\Automating-inline-IR-analysis-for-optimising-synthetic-reactions-MSc-project-1\metadata_utils.py", line 23, in get_probe1_data
    value_of_node = child.get_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 155, in get_value
    result = self.get_data_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 164, in get_data_value
    return self.get_attribute(ua.AttributeIds.Value)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 276, in get_attribute
    result[0].StatusCode.check()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\ua\uatypes.py", line 218, in check
    raise UaStatusCodeError(self.value)
opcua.ua.uaerrors._auto.BadAttributeIdInvalid: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
------------------------------------------------------------

--- ERROR LOG ---
Timestamp: 07-082025_22-01-54
Context: Child node 'ns=2;s=Local.iCIR.Probe1.Trends' does not support attribute 'Value'. Skipped. (BadAttributeIdInvalid)
Exception: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
Traceback:
Traceback (most recent call last):
  File "c:\Users\FlowChemIR_User\Desktop\AGS Users\Meg\Automating-inline-IR-analysis-for-optimising-synthetic-reactions-MSc-project-1\metadata_utils.py", line 23, in get_probe1_data
    value_of_node = child.get_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 155, in get_value
    result = self.get_data_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 164, in get_data_value
    return self.get_attribute(ua.AttributeIds.Value)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 276, in get_attribute
    result[0].StatusCode.check()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\ua\uatypes.py", line 218, in check
    raise UaStatusCodeError(self.value)
opcua.ua.uaerrors._auto.BadAttributeIdInvalid: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
------------------------------------------------------------

--- ERROR LOG ---
Timestamp: 07-082025_22-01-54
Context: Child node 'ns=2;s=Local.iCIR.Probe1.Triggers' does not support attribute 'Value'. Skipped. (BadAttributeIdInvalid)
Exception: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
Traceback:
Traceback (most recent call last):
  File "c:\Users\FlowChemIR_User\Desktop\AGS Users\Meg\Automating-inline-IR-analysis-for-optimising-synthetic-reactions-MSc-project-1\metadata_utils.py", line 23, in get_probe1_data
    value_of_node = child.get_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 155, in get_value
    result = self.get_data_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 164, in get_data_value
    return self.get_attribute(ua.AttributeIds.Value)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 276, in get_attribute
    result[0].StatusCode.check()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\ua\uatypes.py", line 218, in check
    raise UaStatusCodeError(self.value)
opcua.ua.uaerrors._auto.BadAttributeIdInvalid: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
------------------------------------------------------------

--- ERROR LOG ---
Timestamp: 07-082025_22-01-54
Context: Child node 'ns=2;s=Local.iCIR.Probe1.Methods' does not support attribute 'Value'. Skipped. (BadAttributeIdInvalid)
Exception: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
Traceback:
Traceback (most recent call last):
  File "c:\Users\FlowChemIR_User\Desktop\AGS Users\Meg\Automating-inline-IR-analysis-for-optimising-synthetic-reactions-MSc-project-1\metadata_utils.py", line 23, in get_probe1_data
    value_of_node = child.get_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 155, in get_value
    result = self.get_data_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 164, in get_data_value
    return self.get_attribute(ua.AttributeIds.Value)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 276, in get_attribute
    result[0].StatusCode.check()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\ua\uatypes.py", line 218, in check
    raise UaStatusCodeError(self.value)
opcua.ua.uaerrors._auto.BadAttributeIdInvalid: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
------------------------------------------------------------

--- ERROR LOG ---
Timestamp: 07-082025_22-02-24
Context: Child node 'ns=2;s=Local.iCIR.Probe1.Trends' does not support attribute 'Value'. Skipped. (BadAttributeIdInvalid)
Exception: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
Traceback:
Traceback (most recent call last):
  File "c:\Users\FlowChemIR_User\Desktop\AGS Users\Meg\Automating-inline-IR-analysis-for-optimising-synthetic-reactions-MSc-project-1\metadata_utils.py", line 23, in get_probe1_data
    value_of_node = child.get_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 155, in get_value
    result = self.get_data_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 164, in get_data_value
    return self.get_attribute(ua.AttributeIds.Value)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 276, in get_attribute
    result[0].StatusCode.check()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\ua\uatypes.py", line 218, in check
    raise UaStatusCodeError(self.value)
opcua.ua.uaerrors._auto.BadAttributeIdInvalid: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
------------------------------------------------------------

--- ERROR LOG ---
Timestamp: 07-082025_22-02-24
Context: Child node 'ns=2;s=Local.iCIR.Probe1.Triggers' does not support attribute 'Value'. Skipped. (BadAttributeIdInvalid)
Exception: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
Traceback:
Traceback (most recent call last):
  File "c:\Users\FlowChemIR_User\Desktop\AGS Users\Meg\Automating-inline-IR-analysis-for-optimising-synthetic-reactions-MSc-project-1\metadata_utils.py", line 23, in get_probe1_data
    value_of_node = child.get_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 155, in get_value
    result = self.get_data_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 164, in get_data_value
    return self.get_attribute(ua.AttributeIds.Value)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 276, in get_attribute
    result[0].StatusCode.check()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\ua\uatypes.py", line 218, in check
    raise UaStatusCodeError(self.value)
opcua.ua.uaerrors._auto.BadAttributeIdInvalid: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
------------------------------------------------------------

--- ERROR LOG ---
Timestamp: 07-082025_22-02-24
Context: Child node 'ns=2;s=Local.iCIR.Probe1.Methods' does not support attribute 'Value'. Skipped. (BadAttributeIdInvalid)
Exception: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
Traceback:
Traceback (most recent call last):
  File "c:\Users\FlowChemIR_User\Desktop\AGS Users\Meg\Automating-inline-IR-analysis-for-optimising-synthetic-reactions-MSc-project-1\metadata_utils.py", line 23, in get_probe1_data
    value_of_node = child.get_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 155, in get_value
    result = self.get_data_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 164, in get_data_value
    return self.get_attribute(ua.AttributeIds.Value)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 276, in get_attribute
    result[0].StatusCode.check()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\ua\uatypes.py", line 218, in check
    raise UaStatusCodeError(self.value)
opcua.ua.uaerrors._auto.BadAttributeIdInvalid: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
------------------------------------------------------------

--- ERROR LOG ---
Timestamp: 07-082025_22-02-54
Context: Child node 'ns=2;s=Local.iCIR.Probe1.Trends' does not support attribute 'Value'. Skipped. (BadAttributeIdInvalid)
Exception: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
Traceback:
Traceback (most recent call last):
  File "c:\Users\FlowChemIR_User\Desktop\AGS Users\Meg\Automating-inline-IR-analysis-for-optimising-synthetic-reactions-MSc-project-1\metadata_utils.py", line 23, in get_probe1_data
    value_of_node = child.get_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 155, in get_value
    result = self.get_data_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 164, in get_data_value
    return self.get_attribute(ua.AttributeIds.Value)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 276, in get_attribute
    result[0].StatusCode.check()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\ua\uatypes.py", line 218, in check
    raise UaStatusCodeError(self.value)
opcua.ua.uaerrors._auto.BadAttributeIdInvalid: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
------------------------------------------------------------

--- ERROR LOG ---
Timestamp: 07-082025_22-02-54
Context: Child node 'ns=2;s=Local.iCIR.Probe1.Triggers' does not support attribute 'Value'. Skipped. (BadAttributeIdInvalid)
Exception: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
Traceback:
Traceback (most recent call last):
  File "c:\Users\FlowChemIR_User\Desktop\AGS Users\Meg\Automating-inline-IR-analysis-for-optimising-synthetic-reactions-MSc-project-1\metadata_utils.py", line 23, in get_probe1_data
    value_of_node = child.get_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 155, in get_value
    result = self.get_data_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 164, in get_data_value
    return self.get_attribute(ua.AttributeIds.Value)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 276, in get_attribute
    result[0].StatusCode.check()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\ua\uatypes.py", line 218, in check
    raise UaStatusCodeError(self.value)
opcua.ua.uaerrors._auto.BadAttributeIdInvalid: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
------------------------------------------------------------

--- ERROR LOG ---
Timestamp: 07-082025_22-02-54
Context: Child node 'ns=2;s=Local.iCIR.Probe1.Methods' does not support attribute 'Value'. Skipped. (BadAttributeIdInvalid)
Exception: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
Traceback:
Traceback (most recent call last):
  File "c:\Users\FlowChemIR_User\Desktop\AGS Users\Meg\Automating-inline-IR-analysis-for-optimising-synthetic-reactions-MSc-project-1\metadata_utils.py", line 23, in get_probe1_data
    value_of_node = child.get_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 155, in get_value
    result = self.get_data_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 164, in get_data_value
    return self.get_attribute(ua.AttributeIds.Value)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 276, in get_attribute
    result[0].StatusCode.check()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\ua\uatypes.py", line 218, in check
    raise UaStatusCodeError(self.value)
opcua.ua.uaerrors._auto.BadAttributeIdInvalid: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
------------------------------------------------------------

--- ERROR LOG ---
Timestamp: 07-082025_22-03-24
Context: Child node 'ns=2;s=Local.iCIR.Probe1.Trends' does not support attribute 'Value'. Skipped. (BadAttributeIdInvalid)
Exception: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
Traceback:
Traceback (most recent call last):
  File "c:\Users\FlowChemIR_User\Desktop\AGS Users\Meg\Automating-inline-IR-analysis-for-optimising-synthetic-reactions-MSc-project-1\metadata_utils.py", line 23, in get_probe1_data
    value_of_node = child.get_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 155, in get_value
    result = self.get_data_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 164, in get_data_value
    return self.get_attribute(ua.AttributeIds.Value)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 276, in get_attribute
    result[0].StatusCode.check()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\ua\uatypes.py", line 218, in check
    raise UaStatusCodeError(self.value)
opcua.ua.uaerrors._auto.BadAttributeIdInvalid: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
------------------------------------------------------------

--- ERROR LOG ---
Timestamp: 07-082025_22-03-24
Context: Child node 'ns=2;s=Local.iCIR.Probe1.Triggers' does not support attribute 'Value'. Skipped. (BadAttributeIdInvalid)
Exception: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
Traceback:
Traceback (most recent call last):
  File "c:\Users\FlowChemIR_User\Desktop\AGS Users\Meg\Automating-inline-IR-analysis-for-optimising-synthetic-reactions-MSc-project-1\metadata_utils.py", line 23, in get_probe1_data
    value_of_node = child.get_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 155, in get_value
    result = self.get_data_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 164, in get_data_value
    return self.get_attribute(ua.AttributeIds.Value)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 276, in get_attribute
    result[0].StatusCode.check()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\ua\uatypes.py", line 218, in check
    raise UaStatusCodeError(self.value)
opcua.ua.uaerrors._auto.BadAttributeIdInvalid: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
------------------------------------------------------------

--- ERROR LOG ---
Timestamp: 07-082025_22-03-24
Context: Child node 'ns=2;s=Local.iCIR.Probe1.Methods' does not support attribute 'Value'. Skipped. (BadAttributeIdInvalid)
Exception: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
Traceback:
Traceback (most recent call last):
  File "c:\Users\FlowChemIR_User\Desktop\AGS Users\Meg\Automating-inline-IR-analysis-for-optimising-synthetic-reactions-MSc-project-1\metadata_utils.py", line 23, in get_probe1_data
    value_of_node = child.get_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 155, in get_value
    result = self.get_data_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 164, in get_data_value
    return self.get_attribute(ua.AttributeIds.Value)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 276, in get_attribute
    result[0].StatusCode.check()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\ua\uatypes.py", line 218, in check
    raise UaStatusCodeError(self.value)
opcua.ua.uaerrors._auto.BadAttributeIdInvalid: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
------------------------------------------------------------

--- ERROR LOG ---
Timestamp: 07-082025_22-03-54
Context: Child node 'ns=2;s=Local.iCIR.Probe1.Trends' does not support attribute 'Value'. Skipped. (BadAttributeIdInvalid)
Exception: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
Traceback:
Traceback (most recent call last):
  File "c:\Users\FlowChemIR_User\Desktop\AGS Users\Meg\Automating-inline-IR-analysis-for-optimising-synthetic-reactions-MSc-project-1\metadata_utils.py", line 23, in get_probe1_data
    value_of_node = child.get_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 155, in get_value
    result = self.get_data_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 164, in get_data_value
    return self.get_attribute(ua.AttributeIds.Value)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 276, in get_attribute
    result[0].StatusCode.check()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\ua\uatypes.py", line 218, in check
    raise UaStatusCodeError(self.value)
opcua.ua.uaerrors._auto.BadAttributeIdInvalid: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
------------------------------------------------------------

--- ERROR LOG ---
Timestamp: 07-082025_22-03-54
Context: Child node 'ns=2;s=Local.iCIR.Probe1.Triggers' does not support attribute 'Value'. Skipped. (BadAttributeIdInvalid)
Exception: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
Traceback:
Traceback (most recent call last):
  File "c:\Users\FlowChemIR_User\Desktop\AGS Users\Meg\Automating-inline-IR-analysis-for-optimising-synthetic-reactions-MSc-project-1\metadata_utils.py", line 23, in get_probe1_data
    value_of_node = child.get_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 155, in get_value
    result = self.get_data_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 164, in get_data_value
    return self.get_attribute(ua.AttributeIds.Value)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 276, in get_attribute
    result[0].StatusCode.check()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\ua\uatypes.py", line 218, in check
    raise UaStatusCodeError(self.value)
opcua.ua.uaerrors._auto.BadAttributeIdInvalid: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
------------------------------------------------------------

--- ERROR LOG ---
Timestamp: 07-082025_22-03-54
Context: Child node 'ns=2;s=Local.iCIR.Probe1.Methods' does not support attribute 'Value'. Skipped. (BadAttributeIdInvalid)
Exception: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
Traceback:
Traceback (most recent call last):
  File "c:\Users\FlowChemIR_User\Desktop\AGS Users\Meg\Automating-inline-IR-analysis-for-optimising-synthetic-reactions-MSc-project-1\metadata_utils.py", line 23, in get_probe1_data
    value_of_node = child.get_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 155, in get_value
    result = self.get_data_value()
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 164, in get_data_value
    return self.get_attribute(ua.AttributeIds.Value)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\common\node.py", line 276, in get_attribute
    result[0].StatusCode.check()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\FlowChemIR_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\opcua\ua\uatypes.py", line 218, in check
    raise UaStatusCodeError(self.value)
opcua.ua.uaerrors._auto.BadAttributeIdInvalid: "The attribute is not supported for the specified Node."(BadAttributeIdInvalid)
------------------------------------------------------------

--- ERROR LOG ---
Timestamp: 07-082025_22-03-54
Context: logs\MON5.2_Clone_test_run_2_3_2\error_log_07-08-2025_22-00-54.txt
Exception: User interrupted logging (Ctrl+C)
Traceback:
Traceback (most recent call last):
  File "c:\Users\FlowChemIR_User\Desktop\AGS Users\Meg\Automating-inline-IR-analysis-for-optimising-synthetic-reactions-MSc-project-1\main.py", line 241, in main
    except Exception as e:
        ^^^^^^^^^^^^^
KeyboardInterrupt
------------------------------------------------------------
